// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewLab.Data;

#nullable disable

namespace NewLab.Migrations
{
    [DbContext(typeof(NewLabDbContext))]
    [Migration("20260724020022_AlterPatientAgeToDecimal")]
    partial class AlterPatientAgeToDecimal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewLab.Models.Domain.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("NewLab.Models.Domain.BarcodeSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LabelHeight")
                        .HasColumnType("int");

                    b.Property<int>("LabelWidth")
                        .HasColumnType("int");

                    b.Property<int>("OffsetX")
                        .HasColumnType("int");

                    b.Property<int>("OffsetY")
                        .HasColumnType("int");

                    b.Property<bool>("PrintFileCodeWithAll")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("BarcodeSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LabelHeight = 25,
                            LabelWidth = 38,
                            OffsetX = 0,
                            OffsetY = 0,
                            PrintFileCodeWithAll = false
                        });
                });

            modelBuilder.Entity("NewLab.Models.Domain.CalculationConstant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConstantName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ConstantValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TestType", "ConstantName")
                        .IsUnique();

                    b.ToTable("CalculationConstants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConstantName = "AgeUnder1",
                            ConstantValue = 8.25m,
                            TestType = "Hgb",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ConstantName = "Age1To12",
                            ConstantValue = 7.50m,
                            TestType = "Hgb",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ConstantName = "MaleOver12",
                            ConstantValue = 6.25m,
                            TestType = "Hgb",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            ConstantName = "FemaleOver12",
                            ConstantValue = 6.75m,
                            TestType = "Hgb",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            ConstantName = "HctMultiplier",
                            ConstantValue = 3.3m,
                            TestType = "CBC",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            ConstantName = "ISI",
                            ConstantValue = 1.0m,
                            TestType = "PT",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            ConstantName = "ControlTime",
                            ConstantValue = 12.0m,
                            TestType = "PT",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            ConstantName = "ControlTime",
                            ConstantValue = 30.0m,
                            TestType = "PTT",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NewLab.Models.Domain.LabTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArabicName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ArrangeNumber")
                        .HasColumnType("int");

                    b.Property<string>("BillNameLarge")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BillNameSmall")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Collection")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DefaultSpecimenTypeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ExternalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ExternalReferralId")
                        .HasColumnType("int");

                    b.Property<string>("HistoryName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAddWithGroup")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMainTest")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrintWithOther")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRoutine")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSeeReport")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSentExternal")
                        .HasColumnType("bit");

                    b.Property<decimal>("LabToLabPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LogGroup")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentLabTestId")
                        .HasColumnType("int");

                    b.Property<decimal>("PatientPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PromptQuestion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReportNameLarge")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReportNameSmall")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TestGroupId")
                        .HasColumnType("int");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TestTimeDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DefaultSpecimenTypeId");

                    b.HasIndex("ExternalReferralId");

                    b.HasIndex("ParentLabTestId");

                    b.HasIndex("TestGroupId");

                    b.ToTable("LabTests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArabicName = "سكر",
                            ArrangeNumber = 1,
                            Code = "GLU",
                            IsActive = true,
                            IsAddWithGroup = false,
                            IsMainTest = false,
                            IsPrintWithOther = false,
                            IsRoutine = true,
                            IsSeeReport = false,
                            IsSentExternal = false,
                            LabToLabPrice = 30m,
                            PatientPrice = 10m,
                            ReportNameLarge = "Glucose",
                            TestGroupId = 1,
                            TestName = "Glucose",
                            TestTimeDays = 0
                        },
                        new
                        {
                            Id = 2,
                            ArabicName = "هموغلوبين",
                            ArrangeNumber = 2,
                            Code = "HGB",
                            IsActive = true,
                            IsAddWithGroup = false,
                            IsMainTest = false,
                            IsPrintWithOther = false,
                            IsRoutine = true,
                            IsSeeReport = false,
                            IsSentExternal = false,
                            LabToLabPrice = 35m,
                            PatientPrice = 15m,
                            ReportNameLarge = "Hemoglobin",
                            TestGroupId = 2,
                            TestName = "Hemoglobin",
                            TestTimeDays = 0
                        },
                        new
                        {
                            Id = 3,
                            ArabicName = "تحليل بول",
                            ArrangeNumber = 3,
                            Code = "UAC",
                            IsActive = true,
                            IsAddWithGroup = false,
                            IsMainTest = false,
                            IsPrintWithOther = false,
                            IsRoutine = true,
                            IsSeeReport = false,
                            IsSentExternal = false,
                            LabToLabPrice = 20m,
                            PatientPrice = 8m,
                            ReportNameLarge = "Urine Analysis",
                            TestGroupId = 3,
                            TestName = "Urine Analysis",
                            TestTimeDays = 0
                        });
                });

            modelBuilder.Entity("NewLab.Models.Domain.LabTestElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArrangeNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsMainTest")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ParentLabTestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentLabTestId");

                    b.ToTable("LabTestElements");
                });

            modelBuilder.Entity("NewLab.Models.Domain.NormalRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeFrom")
                        .HasColumnType("int");

                    b.Property<int>("AgeTo")
                        .HasColumnType("int");

                    b.Property<int>("AgeUnit")
                        .HasColumnType("int");

                    b.Property<string>("CriticalComment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CriticalFlag")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("CriticalHighLimit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CriticalLowLimit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CriticalRangeText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("HighComment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HighFlag")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("HighLimit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("LabTestId")
                        .HasColumnType("int");

                    b.Property<string>("LowComment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LowFlag")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("LowLimit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("NormalRangeText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TestUnit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LabTestId", "Gender", "AgeFrom", "AgeTo", "AgeUnit");

                    b.ToTable("NormalRanges");
                });

            modelBuilder.Entity("NewLab.Models.Domain.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("AgeValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BillingSystem")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeliveredByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("DiscountIsPercent")
                        .HasColumnType("bit");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ExternalSpecimenTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("FastingHours")
                        .HasColumnType("int");

                    b.Property<string>("FileCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("HasAntibiotic")
                        .HasColumnType("bit");

                    b.Property<bool>("HasAntiviralTreatment")
                        .HasColumnType("bit");

                    b.Property<bool>("HasLiverTreatment")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFasting")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImportant")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnAnticoagulant")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPregnant")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSmoker")
                        .HasColumnType("bit");

                    b.Property<string>("LabId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("ReferralHiddenOnReport")
                        .HasColumnType("bit");

                    b.Property<int?>("ReferralId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeliveredByUserId");

                    b.HasIndex("ExternalSpecimenTypeId");

                    b.HasIndex("FileCode")
                        .IsUnique()
                        .HasFilter("[FileCode] IS NOT NULL");

                    b.HasIndex("LabId")
                        .IsUnique()
                        .HasFilter("[LabId] IS NOT NULL");

                    b.HasIndex("ReferralId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("NewLab.Models.Domain.PatientCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodeType")
                        .HasColumnType("int");

                    b.Property<string>("CodeValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodeValue");

                    b.HasIndex("PatientId", "CodeType")
                        .IsUnique();

                    b.ToTable("PatientCodes");
                });

            modelBuilder.Entity("NewLab.Models.Domain.PatientTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DeliveredByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EnteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EnteredByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrinted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("bit");

                    b.Property<int>("LabTestId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientVisitId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PrintedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeliveredByUserId");

                    b.HasIndex("EnteredByUserId");

                    b.HasIndex("LabTestId");

                    b.HasIndex("PrintedByUserId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("PatientVisitId", "LabTestId")
                        .IsUnique();

                    b.ToTable("PatientTests");
                });

            modelBuilder.Entity("NewLab.Models.Domain.PatientVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DailySequenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("FullVisitCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientVisits");
                });

            modelBuilder.Entity("NewLab.Models.Domain.PaymentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("PatientId", "Timestamp");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("NewLab.Models.Domain.Referral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsDefaultLab")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Referrals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercent = 0m,
                            IsDefaultLab = true,
                            Name = "المعمل"
                        });
                });

            modelBuilder.Entity("NewLab.Models.Domain.ReferralPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LabTestId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReferralId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReferralId");

                    b.HasIndex("LabTestId", "ReferralId")
                        .IsUnique();

                    b.ToTable("ReferralPrices");
                });

            modelBuilder.Entity("NewLab.Models.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "System Administrator",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lab Technician",
                            Name = "Technician"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Front Desk Receptionist",
                            Name = "Receptionist"
                        });
                });

            modelBuilder.Entity("NewLab.Models.Domain.SavedComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("LabTestId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("LabTestId", "Type");

                    b.ToTable("SavedComments");
                });

            modelBuilder.Entity("NewLab.Models.Domain.SpecimenType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("SpecimenTypes");
                });

            modelBuilder.Entity("NewLab.Models.Domain.TestGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LogGroup")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("TestGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LogGroup = "CHEM",
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 2,
                            LogGroup = "HEM",
                            Name = "Hematology"
                        },
                        new
                        {
                            Id = 3,
                            LogGroup = "URI",
                            Name = "Urine"
                        });
                });

            modelBuilder.Entity("NewLab.Models.Domain.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlagText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsAbnormal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("bit");

                    b.Property<int>("LabTestElementId")
                        .HasColumnType("int");

                    b.Property<int>("PatientTestId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Value")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LabTestElementId");

                    b.HasIndex("PatientTestId", "LabTestElementId")
                        .IsUnique();

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("NewLab.Models.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NewLab.Models.Domain.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("NewLab.Models.Domain.AuditLog", b =>
                {
                    b.HasOne("NewLab.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewLab.Models.Domain.LabTest", b =>
                {
                    b.HasOne("NewLab.Models.Domain.SpecimenType", "DefaultSpecimenType")
                        .WithMany()
                        .HasForeignKey("DefaultSpecimenTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NewLab.Models.Domain.Referral", "ExternalReferral")
                        .WithMany()
                        .HasForeignKey("ExternalReferralId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NewLab.Models.Domain.LabTest", "ParentLabTest")
                        .WithMany()
                        .HasForeignKey("ParentLabTestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NewLab.Models.Domain.TestGroup", "TestGroup")
                        .WithMany("Tests")
                        .HasForeignKey("TestGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DefaultSpecimenType");

                    b.Navigation("ExternalReferral");

                    b.Navigation("ParentLabTest");

                    b.Navigation("TestGroup");
                });

            modelBuilder.Entity("NewLab.Models.Domain.LabTestElement", b =>
                {
                    b.HasOne("NewLab.Models.Domain.LabTest", "ParentLabTest")
                        .WithMany("Elements")
                        .HasForeignKey("ParentLabTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentLabTest");
                });

            modelBuilder.Entity("NewLab.Models.Domain.NormalRange", b =>
                {
                    b.HasOne("NewLab.Models.Domain.LabTest", "LabTest")
                        .WithMany()
                        .HasForeignKey("LabTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabTest");
                });

            modelBuilder.Entity("NewLab.Models.Domain.Patient", b =>
                {
                    b.HasOne("NewLab.Models.Domain.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NewLab.Models.Domain.User", "DeliveredByUser")
                        .WithMany()
                        .HasForeignKey("DeliveredByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NewLab.Models.Domain.SpecimenType", "ExternalSpecimenType")
                        .WithMany()
                        .HasForeignKey("ExternalSpecimenTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NewLab.Models.Domain.Referral", "Referral")
                        .WithMany()
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("DeliveredByUser");

                    b.Navigation("ExternalSpecimenType");

                    b.Navigation("Referral");
                });

            modelBuilder.Entity("NewLab.Models.Domain.PatientCode", b =>
                {
                    b.HasOne("NewLab.Models.Domain.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("NewLab.Models.Domain.PatientTest", b =>
                {
                    b.HasOne("NewLab.Models.Domain.User", "DeliveredByUser")
                        .WithMany()
                        .HasForeignKey("DeliveredByUserId");

                    b.HasOne("NewLab.Models.Domain.User", "EnteredByUser")
                        .WithMany()
                        .HasForeignKey("EnteredByUserId");

                    b.HasOne("NewLab.Models.Domain.LabTest", "LabTest")
                        .WithMany()
                        .HasForeignKey("LabTestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NewLab.Models.Domain.PatientVisit", "Visit")
                        .WithMany("PatientTests")
                        .HasForeignKey("PatientVisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewLab.Models.Domain.User", "PrintedByUser")
                        .WithMany()
                        .HasForeignKey("PrintedByUserId");

                    b.HasOne("NewLab.Models.Domain.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId");

                    b.Navigation("DeliveredByUser");

                    b.Navigation("EnteredByUser");

                    b.Navigation("LabTest");

                    b.Navigation("PrintedByUser");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("NewLab.Models.Domain.PatientVisit", b =>
                {
                    b.HasOne("NewLab.Models.Domain.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("NewLab.Models.Domain.PaymentTransaction", b =>
                {
                    b.HasOne("NewLab.Models.Domain.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewLab.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewLab.Models.Domain.ReferralPrice", b =>
                {
                    b.HasOne("NewLab.Models.Domain.LabTest", "LabTest")
                        .WithMany("ReferralPrices")
                        .HasForeignKey("LabTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewLab.Models.Domain.Referral", "Referral")
                        .WithMany()
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LabTest");

                    b.Navigation("Referral");
                });

            modelBuilder.Entity("NewLab.Models.Domain.SavedComment", b =>
                {
                    b.HasOne("NewLab.Models.Domain.LabTest", "LabTest")
                        .WithMany()
                        .HasForeignKey("LabTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabTest");
                });

            modelBuilder.Entity("NewLab.Models.Domain.TestResult", b =>
                {
                    b.HasOne("NewLab.Models.Domain.LabTestElement", "Element")
                        .WithMany()
                        .HasForeignKey("LabTestElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NewLab.Models.Domain.PatientTest", "PatientTest")
                        .WithMany()
                        .HasForeignKey("PatientTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("PatientTest");
                });

            modelBuilder.Entity("NewLab.Models.Domain.UserRole", b =>
                {
                    b.HasOne("NewLab.Models.Domain.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewLab.Models.Domain.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewLab.Models.Domain.LabTest", b =>
                {
                    b.Navigation("Elements");

                    b.Navigation("ReferralPrices");
                });

            modelBuilder.Entity("NewLab.Models.Domain.Patient", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("NewLab.Models.Domain.PatientVisit", b =>
                {
                    b.Navigation("PatientTests");
                });

            modelBuilder.Entity("NewLab.Models.Domain.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("NewLab.Models.Domain.TestGroup", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("NewLab.Models.Domain.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
